### ISSUE TITLE
Typo in Classification vs regression?

### ISSUE THREAD

**Issue by Tawfiqh** [life-efficient/Machine-Learning#2]
https://github.com/life-efficient/Machine-Learning/blob/main/2.%20Introduction%20to%20ML/0.%20Overview/Lesson.ipynb

```
## Classification vs regression
Most machine learning problems are parts of supervised machine learning which is further split into:

regression problems (categorical target)
classification problems (continuous target)
```

I think it should have regression as "(continuous target)"
and classification as "(categorical target)"

**Comment by life-efficient** [comment]
💯
